// ************************************************************
// This file is automatically generated by genxdr. Do not edit.
// ************************************************************

package main

import (
	"github.com/calmh/xdr"
)

/*

Post Structure:

 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/                                                               /
\                 Title (length + padded data)                  \
/                                                               /
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/                                                               /
\                         int Structure                         \
/                                                               /
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+


struct Post {
	string Title<>;
	int Content;
}

*/

func (o Post) XDRSize() int {
	return 4 + len(o.Title) + xdr.Padding(len(o.Title)) + 8
}

func (o Post) MarshalXDR() ([]byte, error) {
	buf := make([]byte, o.XDRSize())
	m := &xdr.Marshaller{Data: buf}
	return buf, o.MarshalXDRInto(m)
}

func (o Post) MustMarshalXDR() []byte {
	bs, err := o.MarshalXDR()
	if err != nil {
		panic(err)
	}
	return bs
}

func (o Post) MarshalXDRInto(m *xdr.Marshaller) error {
	m.MarshalString(o.Title)
	m.MarshalUint64(uint64(o.Content))
	return m.Error
}

func (o *Post) UnmarshalXDR(bs []byte) error {
	u := &xdr.Unmarshaller{Data: bs}
	return o.UnmarshalXDRFrom(u)
}
func (o *Post) UnmarshalXDRFrom(u *xdr.Unmarshaller) error {
	o.Title = u.UnmarshalString()
	o.Content = int(u.UnmarshalUint64())
	return u.Error
}
